### ISSUE TITLE
Failure using enable-compression and enable-logging

### ISSUE THREAD

**Issue by systemtrap** [gogatekeeper/gatekeeper#74]
# Failure using enable-compression and enable-logging
## Summary
The options enable-compression and enable-logging can not be used together.

## Environment
docker: quay.io/gogatekeeper/gatekeeper:1.3.0 with --enable-compression and  --enable-logging.

## Expected Results
The usual response from upstream, but compressed. Access is logged by gatekeeper.

## Actual Results
A response with status 200 and an empty body.

## Additional Information
```
Panic: interface conversion: *main.gzipResponseWriter is not middleware.WrapResponseWriter: missing method BytesWritten
goroutine 48 [running]:
runtime/debug.Stack(0x78, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/go-chi/chi/middleware.Recoverer.func1.1(0xc0000f5600, 0xc8d180, 0xc00064e0e0)
	/go/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/middleware/recoverer.go:28 +0x1bf
panic(0xaf8200, 0xc0003841b0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
main.(*oauthProxy).loggingMiddleware.func1(0xc8ce80, 0xc000550040, 0xc0000f5700)
	/src/middleware.go:142 +0x9c
net/http.HandlerFunc.ServeHTTP(0xc0005502c0, 0xc8ce80, 0xc000550040, 0xc0000f5700)
	/usr/local/go/src/net/http/server.go:2042 +0x44
main.gzipMiddleware.func1(0x7faad57f5648, 0xc00057ef80, 0xc0000f5700)
	/src/middleware.go:82 +0x2f7
net/http.HandlerFunc.ServeHTTP(0xc0005502e0, 0x7faad57f5648, 0xc00057ef80, 0xc0000f5700)
	/usr/local/go/src/net/http/server.go:2042 +0x44
main.entrypointMiddleware.func1(0xc8d180, 0xc00064e0e0, 0xc0000f5600)
	/src/middleware.go:109 +0x36c
net/http.HandlerFunc.ServeHTTP(0xc000550300, 0xc8d180, 0xc00064e0e0, 0xc0000f5600)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/go-chi/chi/middleware.Recoverer.func1(0xc8d180, 0xc00064e0e0, 0xc0000f5600)
	/go/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/middleware/recoverer.go:35 +0x83
net/http.HandlerFunc.ServeHTTP(0xc000550320, 0xc8d180, 0xc00064e0e0, 0xc0000f5600)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00005a420, 0xc8d180, 0xc00064e0e0, 0xc0000f5300)
	/go/pkg/mod/github.com/go-chi/chi@v3.3.3+incompatible/mux.go:81 +0x2d1
net/http.serverHandler.ServeHTTP(0xc00064e000, 0xc8d180, 0xc00064e0e0, 0xc0000f5300)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000532000, 0xc8ebc0, 0xc00057e740)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
```

**Comment by p53** [comment]
@systemtrap thank you for reporting, will look at it, seems like bug in implementation, possibly also missing tests

**Comment by p53** [comment]
@systemtrap hi you can try #75 pull request, it will need some additional test/s but should work

**Comment by systemtrap** [comment]
I'll do so. It may take a day or another as I have to setup the build and the containers.

**Comment by p53** [comment]
@systemtrap i will make new release today/tomorrow with this and another fix

**Comment by p53** [comment]
@systemtrap there is 1.3.1-rc1 image, could you try

**Comment by systemtrap** [comment]
I'm sorry for being silent for so long. It works as expected now.
